configuration :
  - name : alice 	
    ip   : 128.237.229.138
    port : 12344
  - name : bob 	
    ip   : 128.237.241.33	
    port : 14255	
  - name : charlie	
    ip   : 128.237.229.138 
    port : 12998	
  - name : daphnie	
    ip   : 128.237.241.33		
    port : 1987	

sendRules :
  - action : drop
    src    : alice
    dest   : bob
    kind   : Ack
    seqNum : 1
  - action : delay
    kind   : Lookup
  - action : duplicate
    src	   : alice
    kind   : Seq

receiveRules :
  - action : duplicate
    src    : alice
    seqNum : 3